export const ACTIVITIES = [
  "Dining at local restaurants",
  "Coffee shops",
  "Bubble tea shops",
  "Bakeries & pastry shops",
  "Food markets, night markets",
  "Shopping for souvenirs",
  "Visiting landmarks and historical sites",
  "Visiting museums and art exhibitions",
  "Amusement parks",
  "Water parks",
  "Mountain climbing",
  "Trekking",
  "Picnics",
  "Adventure activities (zipline, paragliding, surfing…)",
  "Attending festivals",
  "Cultural tours – traditional craft villages",
  "Camping / glamping",
  "Massage",
  "Spa & relaxation",
  "Mud baths, hot springs",
  "Yoga",
  "Meditation",
  "Watching movies at the cinema",
  "Live music shows",
  "Watching performing arts",
  "Karaoke",
  "Bars / pubs",
  "Clubs / nightclubs",
  "Video games",
  "VR gaming",
];
