// export const PLACE_TYPES = [
//   "parking",
//   "art_gallery",
//   "art_studio",
//   "museum",
//   "performing_arts_theater",
//   "amusement_center",
//   "amusement_park",
//   "aquarium",
//   "barbecue_area",
//   "botanical_garden",
//   "childrens_camp",
//   "comedy_club",
//   "concert_hall",
//   "cycling_park",
//   "event_venue",
//   "ferris_wheel",
//   "garden",
//   "hiking_area",
//   "internet_cafe",
//   "karaoke",
//   "movie_rental",
//   "movie_theater",
//   "national_park",
//   "night_club",
//   "observation_deck",
//   "park",
//   "planetarium",
//   "roller_coaster",
//   "skateboard_park",
//   "state_park",
//   "tourist_attraction",
//   "video_arcade",
//   "water_park",
//   "wedding_venue",
//   "wildlife_park",
//   "wildlife_refuge",
//   "zoo",
//   "american_restaurant",
//   "asian_restaurant",
//   "bakery",
//   "bar",
//   "bar_and_grill",
//   "barbecue_restaurant",
//   "breakfast_restaurant",
//   "brunch_restaurant",
//   "buffet_restaurant",
//   "cafe",
//   "cafeteria",
//   "cat_cafe",
//   "chinese_restaurant",
//   "dessert_restaurant",
//   "dessert_shop",
//   "dog_cafe",
//   "fast_food_restaurant",
//   "fine_dining_restaurant",
//   "french_restaurant",
//   "greek_restaurant",
//   "hamburger_restaurant",
//   "ice_cream_shop",
//   "indian_restaurant",
//   "italian_restaurant",
//   "japanese_restaurant",
//   "korean_restaurant",
//   "lebanese_restaurant",
//   "mediterranean_restaurant",
//   "pizza_restaurant",
//   "ramen_restaurant",
//   "restaurant",
//   "seafood_restaurant",
//   "steak_house",
//   "sushi_restaurant",
//   "thai_restaurant",
//   "turkish_restaurant",
//   "vegan_restaurant",
//   "vegetarian_restaurant",
//   "vietnamese_restaurant",
//   "wine_bar",
//   "skin_care_clinic",
//   "spa",
//   "campground",
//   "camping_cabin",
//   "extended_stay_hotel",
//   "rv_park",
//   "beach",
//   "church",
//   "hindu_temple",
//   "barber_shop",
//   "body_art_service",
//   "makeup_artist",
//   "auto_parts_store",
//   "bicycle_store",
//   "department_store",
//   "gift_shop",
//   "market",
//   "shopping_mall",
//   "supermarket",
//   "arena",
//   "fishing_charter",
//   "playground",
//   "ski_resort",
//   "sports_club",
//   "swimming_pool",
// ];

export const PLACE_TYPES = [
  "restaurant",
  "cafe",
  "coffee",
  "coffee shop",
  "tea house",
  "milk tea",
  "street food",
  "fast food",
  "bakery",
  "ice cream",
  "seafood",
  "bbq",
  "buffet",
  "hotpot",
  "vegetarian",
  "vegan",
  "healthy food",
  "bar",
  "pub",
  "wine bar",
  "beer club",

  "karaoke",
  "cinema",
  "movie theater",
  "comedy club",
  "concert hall",
  "live music",
  "nightclub",
  "dance club",
  "amusement park",
  "theme park",
  "arcade",
  "bowling",
  "billiards",
  "pool hall",

  "tourist attraction",
  "museum",
  "art gallery",
  "art museum",
  "historical site",
  "temple",
  "pagoda",
  "church",
  "cathedral",
  "botanical garden",
  "flower garden",
  "zoo",
  "wildlife park",
  "aquarium",
  "planetarium",
  "science center",
  "cultural center",
  "landmark",
  "monument",

  "park",
  "hiking trail",
  "trekking",
  "cycling trail",
  "bike rental",
  "beach",
  "camping",
  "campground",
  "fishing",
  "ski resort",
  "water park",
  "observation deck",
  "viewpoint",

  "spa",
  "massage",
  "wellness",
  "hot spring",
];
